export const JOB_RECOMMENDATIONS = [
    'React',
    'Machine Learning',
    'Backend',
    'iOS',
    'Full Stack',
    'DevOps',
    'UI/UX',
    'Python',
    'Cloud',
    'Embedded',
    'TypeScript',
    'Docker',
    'MERN',
    'API',
    'Rust',
    'Blockchain',
    'Vue',
    'AWS',
    'Game',
    'Angular',
    'Kubernetes',
    'PHP',
    'Go',
    'CI/CD',
    'Web',
    'NLP',
    'Swift',
    'SQL',
    'JavaScript',
    'Azure',
    'Rails',
    'C#',
    'AR/VR',
    'Flutter',
    'MongoDB',
    'Laravel',
    'HTML5',
    'Testing',
    '.NET',
    'Microservices',
    'Ruby',
    'Kotlin',
    'SRE',
    'CSS',
    'Django',
    'WordPress',
    'NoSQL',
    'Spring Boot',
    'Oracle',
    'Performance',
    'Salesforce',
    'GraphQL',
    'PostgreSQL',
    'Big Data',
    'Frontend Developer',
    'Backend Developer',
    'Full Stack Developer',
    'React Developer',
    'Node.js Developer',
    'Python Developer',
    'Java Developer',
    'DevOps Engineer',
    'Data Scientist',
    'UI/UX Designer',
    'Product Manager',
    'Software Engineer',
    'Mobile Developer',
    'iOS Developer',
    'Android Developer',
    'Machine Learning Engineer',
    'Cloud Engineer',
    'Cybersecurity Specialist',
    'Database Administrator',
    'QA Engineer',
    'Database Engineer',
    'Web Developer',
    'Technical Lead',
    'Project Manager',
    'UX Researcher',
    'React Native Developer',
    'Systems Architect',
    'Infrastructure Engineer',
    'Site Reliability Engineer',
    'Cloud Architect',
];

export const REGIONS = [
    { value: '', label: 'All Regions' },
    { value: 'seoul', label: 'Seoul' },
    { value: 'busan', label: 'Busan' },
    { value: 'incheon', label: 'Incheon' },
    { value: 'daegu', label: 'Daegu' },
    { value: 'daejeon', label: 'Daejeon' },
    { value: 'gwangju', label: 'Gwangju' },
    { value: 'remote', label: 'Remote' },
];

export const JOB_TYPES = [
    { value: '', label: 'All Job Types' },
    { value: 'full-time', label: 'Full Time' },
    { value: 'part-time', label: 'Part Time' },
    { value: 'contract', label: 'Contract' },
    { value: 'freelance', label: 'Freelance' },
    { value: 'internship', label: 'Internship' },
];
